# Generated by Django 5.1.7 on 2025-10-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='ExamId',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserExamId',
            field=models.CharField(max_length=6),
        ),
    ]
