# Generated by Django 5.1.7 on 2025-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtc', '0002_alter_exams_examid_alter_users_userexamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='ExamFile',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
